# Generated by Django 4.1.5 on 2023-11-08 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('processed_document', models.FileField(upload_to='processed_documents/')),
            ],
        ),
        migrations.DeleteModel(
            name='UploadedFile',
        ),
    ]
