# Generated by Django 4.1.5 on 2023-11-12 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_processedfile_delete_uploadedfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processedfile',
            name='processed_document',
            field=models.FileField(upload_to=''),
        ),
    ]
