# Generated by Django 4.1.5 on 2023-11-12 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_processedfile_processed_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processedfile',
            name='processed_document',
            field=models.FileField(upload_to='processed_documents/'),
        ),
    ]
